# -*- coding: utf-8 -*-
"""juneweld (2).ipynb

Automatically generated by Colab.

Original file is located at
    https://colab.research.google.com/drive/1u3Nf9_HgE-dtWjEn4j2sQI2e6d3zE-kD
"""

import os
from pathlib import Path
import shutil
 # Change if different
yaml_path =  "/kaggle/working/weldingg.yaml"

# Create the YAML content
yaml_content = """
train: '/kaggle/input/Train-20250527T063028Z-1-001/Train/images'
val: '/kaggle/input/Val-20250527T063028Z-1-001/Val/images'
test: '/kaggle/input/test-20250527T063036Z-1-001/test/images'
nc: 4
names: ['Overweld', 'Undercut', 'Porosity', 'Underfill']
"""

# Save YAML file
with open(yaml_path, "w") as f:
    f.write(yaml_content)

print(f"YAML file saved at: {yaml_path}")

custom_yaml = """
# yolowledX_CBAM.yaml

nc: 4  # number of classes

backbone:
  [
    [Conv, 16, 3, 2],            # Downsample
    [Conv, 32, 3, 2],            # Downsample
    [C3, 32, 1, False],          # Shallow C3 block
    [CBAM, 32],                  # CBAM attention
    [C2f, 64, 1, False],         # Feature fusion
    [C3, 64, 2, False],          # Deep C3 block
    [CBAM, 64]                   # CBAM again at deeper level
  ]

neck:
  [
    [Conv, 128, 3, 2],           # Neck start
    [C3, 128, 2, False],         # Slightly deeper C3
    [SE, 128],                   # Add SEBlock before SPPF
    [SPPF, 128]                  # Spatial Pyramid Pooling - Fast
  ]

head:
  [
    [Detect, nc, anchors]        # YOLO detection head
  ]


"""

# Save to file
with open("yolo11nSE.yaml", "w") as f:
    f.write(custom_yaml.strip())

results1 = model.train(
    data="/kaggle/working/weldingg.yaml",  # your dataset YAML file for welding defects
    epochs=50,
    imgsz=640,
    batch=16,
    device=0,
    name="custom_3_welding",
    save=True,
    augment=True, # enable augmentation like mosaic, mixup, etc.
    visualize= True,
    plots = True
)

# Inference on a single image
results = model.predict(
    source="/kaggle/input/test-20250527T063036Z-1-001/test/images/IMG-20240305-WA0075.jpg",  # or a folder or video /kaggle/input/welding-defects-mnew/test-20250527T063036Z-1-001/test/images/IMG-20240305-WA0075.jpg
    imgsz=640,
    conf=0.25,
    save=True,  # saves prediction image to disk
    device=0
)

# To visualize:
results[0].show()

# To extract prediction details
for r in results:
    print(r.boxes.xyxy)     # [x1, y1, x2, y2]
    print(r.boxes.conf)     # confidence
    print(r.boxes.cls)

from ultralytics import YOLO

# Load existing weights or build model
model = YOLO("/kaggle/working/runs/detect/custom_3_welding/weights/best.pt")
#  /kaggle/working/runs/detect/
# Save model to new path
model.save("/kaggle/working/custom_final_model2.pt")

pip install ultralytics

!zip -r runs.zip runs/

"""## YOLO-CBAM-SE"""

# Python code to write the custom YOLOv8 YAML architecture file

custom_yaml = """
# yolo11n.yaml
# yolo11nCBAM.yaml
# Custom YOLOv8 nano model with CBAM attention and improved backbone for welding defect detection

# yolowledX_CBAM.yaml

nc: 4  # number of classes

backbone:
  [
    [Conv, 16, 3, 2],            # Downsample
    [Conv, 32, 3, 2],            # Downsample
    [C3, 32, 1, False],          # Shallow C3 block
    [CBAM, 32],                  # CBAM attention
    [C2f, 64, 1, False],         # Feature fusion
    [C3, 64, 2, False],          # Deep C3 block
    [CBAM, 64]                   # CBAM again at deeper level
  ]

neck:
  [
    [Conv, 128, 3, 2],           # Neck start
    [C3, 128, 2, False],         # Slightly deeper C3
    [SE, 128],                   # Add SEBlock before SPPF
    [SPPF, 128]                  # Spatial Pyramid Pooling - Fast
  ]

head:
  [
    [Detect, nc, anchors]        # YOLO detection head
  ]


"""

# Save to file
with open("/kaggle/working/yolo11n.yaml", "w") as f:
    f.write(custom_yaml.strip())

print("Custom 'yolo11n.yaml' written successfully.")

from ultralytics import YOLO

# Build a new model from your custom YAML config
model = YOLO("yolo11n.yaml")

# Load pretrained weights (e.g. yolov8n.pt)
model.load("yolov8s.pt")

results = model.train(
    data="/kaggle/working/weldingg.yaml",  # your dataset YAML file for welding defects
    epochs=150,
    imgsz=640,
    batch=16,
    device=0,
    name="custom_yolo4_welding",
    save=True,
    augment=True, # enable augmentation like mosaic, mixup, etc.
    visualize= True,
    plots = True
)

from ultralytics import YOLO

model = YOLO("/kaggle/working/runs/detect/custom_yolo4_welding6/weights/best.pt")

# Evaluate on validation set
val_results = model.val(
    data="/kaggle/working/weldingg.yaml",  # YAML must include val key
    split="val",  # optional, val is default
    imgsz=640,
    device=0
)
# Optionally evaluate on test set

"""## YOLO-ECA"""

# Python code to write the custom YOLOv8 YAML architecture file

custom_yaml = """
nc: 4  # number of classes
depth_multiple: 0.33
width_multiple: 0.25

anchors:
  - [10,13, 16,30, 33,23]       # P3/8
  - [30,61, 62,45, 59,119]      # P4/16
  - [116,90, 156,198, 373,326]  # P5/32

backbone:
  [
    [Conv, 16, 3, 2],            # Downsample
    [Conv, 32, 3, 2],            # Downsample
    [C3, 32, 2, False],          # Slightly deeper C3
    [ECA, 32],                   # Efficient channel attention
    [C2f, 64, 2, False],         # Feature reuse fusion
    [C3, 64, 2, False],          # Deep C3
    [ECA, 64]                    # Attention again deeper
  ]

neck:
  [
    [Conv, 128, 3, 2],           # Downsample
    [C3, 128, 2, False],         # More depth in neck
    [ECA, 128],                  # Channel recalibration
    [SPP, 128]                   # Classic Spatial Pyramid Pooling
  ]

head:
  [
    [Detect, nc, anchors]        # YOLOv8 detection head
  ]
"""

# Save to file
with open("/kaggle/working/yolo11n.yaml", "w") as f:
    f.write(custom_yaml.strip())

print("Custom 'yolo11n.yaml' written successfully.")

from ultralytics import YOLO

# Build a new model from your custom YAML config
model = YOLO("yolo11n.yaml")

# Load pretrained weights (e.g. yolov8n.pt)
model.load("yolov8s.pt")

results = model.train(
    data="/kaggle/working/weldingg.yaml",  # your dataset YAML file for welding defects
    epochs=100,
    imgsz=640,
    batch=16,
    device=0,
    name="custom_yol_welding",
    save=True,
    augment=True, # enable augmentation like mosaic, mixup, etc.
    visualize= True,
    plots = True
)

# Optionally evaluate on test set
test_results = model.val(
    data="/kaggle/working/weldingg.yaml",  # test must be defined in YAML
    split="test",
    imgsz=640,
    device=0
)

"""## YOLO-SPPF

"""

# Python code to write the custom YOLOv8 YAML architecture file

custom_yaml = """
nc: 4  # number of classes

backbone:
  [
    [Conv, 16, 3, 2],         # Stage 1
    [Conv, 32, 3, 2],         # Stage 2
    [C3, 32, 1, False],       # Light residual block

    [Conv, 64, 3, 2],         # Stage 3
    [C3, 64, 2, False],       # Deeper rep

    [Conv, 128, 3, 2],        # Stage 4
    [C3, 128, 2],             # Bottleneck

    [Conv, 256, 3, 2],        # Stage 5
    [C3, 256, 1],             # Compression
  ]

neck:
  [
    [SPPF, 256],              # SPPF at the end of backbone
    [Conv, 128, 1, 1],        # Reduce channels
    [C3, 128, 2],             # Refinement
    [Conv, 64, 1, 1],         # Pyramid building
    [C3, 64, 1],              # More feature learning
  ]

head:
  [
    [Detect, nc, anchors]
  ]


"""

# Save to file
with open("/kaggle/working/yolo11n.yaml", "w") as f:
    f.write(custom_yaml.strip())

print("Custom 'yolo11n.yaml' written successfully.")

from ultralytics import YOLO

# Build a new model from your custom YAML config
model = YOLO("yolo11n.yaml")

# Load pretrained weights (e.g. yolov8n.pt)
model.load("yolov8s.pt")

results = model.train(
    data="/kaggle/working/weldingg.yaml",  # your dataset YAML file for welding defects
    epochs=50,
    imgsz=640,
    batch=16,
    device=0,
    name="custom_yolo33_welding",
    save=True,
    augment=True, # enable augmentation like mosaic, mixup, etc.
    visualize= True,
    plots = True
)

from ultralytics import YOLO

model = YOLO("/kaggle/working/runs/detect/custom_yolo33_welding/weights/best.pt")

# Evaluate on validation set
val_results = model.val(
    data="/kaggle/working/weldingg.yaml",  # YAML must include val key
    split="val",  # optional, val is default
    imgsz=640,
    device=0
)

