# -*- coding: utf-8 -*-
"""Models.ipynb

Automatically generated by Colab.

Original file is located at
    https://colab.research.google.com/drive/1aisQCBUGnCTKltTIgUdCr4kj23gYGQG_
"""

!pip install thop
!pip install ultralytics

"""# 1st"""

from thop import profile
from ultralytics import YOLO
import torch

model = YOLO("/kaggle/input/modell/1st/kaggle/working/runs/detect/train4/weights/best.pt")
dummy_input = torch.randn(1, 3, 640, 640).to("cpu")
flops, params = profile(model.model.to("cpu"), inputs=(dummy_input,))
print(f"FLOPs: {flops/1e9:.2f} GFLOPs | Params: {params/1e6:.2f}M")

"""# 2. ECA"""

from thop import profile
from ultralytics import YOLO
import torch

model = YOLO("/kaggle/input/modell/ECA/runs/detect/custom_yolo_welding/weights/best.pt")
dummy_input = torch.randn(1, 3, 640, 640).to("cpu")
flops, params = profile(model.model.to("cpu"), inputs=(dummy_input,))
print(f"FLOPs: {flops/1e9:.2f} GFLOPs | Params: {params/1e6:.2f}M")

import torch
from thop import profile
from ultralytics import YOLO
import torch

"""# Model- Novel"""

dummy_input = torch.randn(1, 3, 640, 640).to("cpu")
flops, params = profile(model.model.to("cpu"), inputs=(dummy_input,))
print(f"FLOPs: {flops/1e9:.2f} GFLOPs | Params: {params/1e6:.2f}M")

from thop import profile
from ultralytics import YOLO
import torch

model = YOLO("/kaggle/input/modell/combo/runs/detect/custom_yolo4_welding6/weights/best.pt")
dummy_input = torch.randn(1, 3, 640, 640).to("cpu")
flops, params = profile(model.model.to("cpu"), inputs=(dummy_input,))
print(f"FLOPs: {flops/1e9:.2f} GFLOPs | Params: {params/1e6:.2f}M")

"""# YOLO-CBAM-SE"""

from thop import profile
from ultralytics import YOLO
import torch

model = YOLO("/kaggle/input/modell/cbam combo 3/1st/kaggle/working/runs/detect/train4/weights/best.pt")
dummy_input = torch.randn(1, 3, 640, 640).to("cpu")
flops, params = profile(model.model.to("cpu"), inputs=(dummy_input,))
print(f"FLOPs: {flops/1e9:.2f} GFLOPs | Params: {params/1e6:.2f}M")

from thop import profile
from ultralytics import YOLO
import torch

model = YOLO("/kaggle/input/modell/cbam combo 3/runs/detect/custom_yolo33_welding/weights/best.pt")
dummy_input = torch.randn(1, 3, 640, 640).to("cpu")
flops, params = profile(model.model.to("cpu"), inputs=(dummy_input,))
print(f"FLOPs: {flops/1e9:.2f} GFLOPs | Params: {params/1e6:.2f}M")

from thop import profile
from ultralytics import YOLO
import torch

model = YOLO("/kaggle/input/modell/custom_final_model2.pt")
dummy_input = torch.randn(1, 3, 640, 640).to("cpu")
flops, params = profile(model.model.to("cpu"), inputs=(dummy_input,))
print(f"FLOPs: {flops/1e9:.2f} GFLOPs | Params: {params/1e6:.2f}M")

import os
from pathlib import Path
import shutil
 # Change if different
yaml_path =  "/kaggle/working/weldingg.yaml"

# Create the YAML content
yaml_content = """
train: '/kaggle/input/weldingdata/Train-20250527T063028Z-1-001/Train/images'
val: '/kaggle/input/weldingdata/Val-20250527T063028Z-1-001/Val/images'
test: '/kaggle/input/weldingdata/test-20250527T063036Z-1-001/test/images'
nc: 4
names: ['Overweld', 'Undercut', 'Porosity', 'Underfill']
"""

# Save YAML file
with open(yaml_path, "w") as f:
    f.write(yaml_content)

print(f"YAML file saved at: {yaml_path}")

from ultralytics import YOLO
model = YOLO("/kaggle/input/modell/runs (1)/runs/detect/custom_yolo4_welding_aug2/weights/best.pt")
# Evaluate again
results = model.val()

"""## YOLOv8n"""

from ultralytics import YOLO

modell = YOLO('yolov8n.pt')
modell.train(data="/kaggle/working/weldingg.yaml",
            epochs=30,
            imgsz=640,
            batch=16,
            name="custo",
            optimizer='SGD',
            visualize=True,
            plots=True,
            save=True
        )

from ultralytics import YOLO

model = YOLO("/kaggle/working/runs/detect/custo2/weights/best.pt")
val_results = model.val(
    data="/kaggle/working/weldingg.yaml",
    split="val",  # optional, val is default
    imgsz=640,
    device=0
)

!zip -r runs-yolo_8n.zip runs/

