# -*- coding: utf-8 -*-
"""yoov8ms-newc (1).ipynb

Automatically generated by Colab.

Original file is located at
    https://colab.research.google.com/drive/1vqKwR8FRqHnbCjUScC0dxQ4RJnI89dgm
"""

pip install ultralytics

import os
from pathlib import Path
import shutil
 # Change if different
yaml_path =  "/kaggle/working/weldingg.yaml"

# Create the YAML content
yaml_content = """
train: '/kaggle/input/weldingdata/Train-20250527T063028Z-1-001/Train/images'
#train: /kaggle/working/Balance_Dataset_augmented/images
val: '/kaggle/input/weldingdata/Val-20250527T063028Z-1-001/Val/images'
test: '/kaggle/input/weldingdata/test-20250527T063036Z-1-001/test/images'
nc: 4
names: ['Overweld', 'Undercut', 'Porosity', 'Underfill']
"""

# Save YAML file
with open(yaml_path, "w") as f:
    f.write(yaml_content)

print(f"YAML file saved at: {yaml_path}")

from ultralytics import YOLO

# Build a new model from your custom YAML config
model = YOLO("yolo12n.pt")
results = model.train(
    data="/kaggle/working/weldingg.yaml",
    epochs=30,                       # Train longer
    imgsz=640,
    batch=16,
    device=0,
    name="yolo11n",
    optimizer="SGD",               # Better for transformer                  # Cosine LR decay
    save=True,
    plots=True
)

custom_yaml = """

nc: 4  # number of classes
depth_multiple: 1.0
width_multiple: 1.0

backbone:
  [
    [Conv, 64, 3, 2],         # 320 -> 160
    [Conv, 128, 3, 2],        # 160 -> 80
    [C2f, 128, 3],            # Use C2f (YOLOv8 module) not C3
    [CBAM, 128],              # minor attention tweak
    [Conv, 256, 3, 2],        # 80 -> 40
    [C2f, 256, 6],
    [Conv, 512, 3, 2],        # 40 -> 20
    [C2f, 512, 6],
    [Conv, 1024, 3, 2],       # 20 -> 10
    [C2f, 1024, 3],
  ]

neck:
  [
    [SPPF, 1024],
    [Conv, 512, 1, 1],
    [nn.Upsample, None, 2, nearest],
    [Concat, [6, 4]],         # P4 + P3
    [C2f, 512, 3],
    [Conv, 256, 1, 1],
    [nn.Upsample, None, 2, nearest],
    [Concat, [2, 1]],
    [C2f, 256, 3],
    [Conv, 256, 3, 2],
    [Concat, [8, 9]],
    [C2f, 512, 3],
    [Conv, 512, 3, 2],
    [Concat, [5, 12]],
    [C2f, 1024, 3],
  ]

head:
  [[Detect, [256, 512, 1024]]]

"""


# Save YAML
with open("/kaggle/working/yolo11n.yaml", "w") as f:
    f.write(custom_yaml.strip())

print("Custom model YAML saved as yolo11n.yaml")

from ultralytics import YOLO

# Build a new model from your custom YAML config
modell = YOLO("yolo11n.yaml")
modell.load("yolov8m.pt")

results = modell.train(
    data="/kaggle/working/weldingg.yaml",
    epochs=150,                       # Train longer
    imgsz=640,
    batch=16,
    device=0,
    name="yolo11n",
    optimizer="SGD",               # Better for transformer                  # Cosine LR decay
    save=True,
    plots=True
)

"""## YOLOv8s"""

from ultralytics import YOLO

model = YOLO('yolov8s.pt')
model.train(data="/kaggle/working/weldingg.yaml",
            epochs=20,
            imgsz=640,
            batch=16,
            name="custo",
            optimizer='SGD',
            visualize=True,
            plots=True,
            save=True
        )

from ultralytics import YOLO
model = YOLO("/kaggle/working/runs/detect/custo4/weights/best.pt")
val_results = model.val(
    data="/kaggle/working/weldingg.yaml",
    split="val",
    imgsz=640,
    device=0
)

"""## YOLOv8m"""

from ultralytics import YOLO

modell = YOLO('yolov8m.pt')
modell.train(data="/kaggle/working/weldingg.yaml",
            epochs=30,
            imgsz=640,
            batch=16,
            name="custo",
            optimizer='SGD',
            visualize=True,
            plots=True,
            save=True
        )

from ultralytics import YOLO
model = YOLO("/kaggle/working/runs/detect/custo4/weights/best.pt")
val_results = model.val(
    data="/kaggle/working/weldingg.yaml",
    split="val",
    imgsz=640,
    device=0
)

"""## YOLO novel"""

custom_yaml= """
nc: 4
backbone:
  [
    [Conv, 32, 3, 2],
    [Conv, 64, 3, 2],
    [C3, 64, 1],
    [CBAM, 64],              # Only one CBAM
    [C2f, 128, 1],
    [C3, 128, 2],
    # Removed SE here
    [Conv, 256, 3, 2],
    [C3, 256, 2]
  ]
neck:
  [
    [Conv, 256, 3, 1],
    [C3, 256, 1],
    [SPPF, 256],
    [TransformerLayer, 256, 4],
    [PAN, 256, 128, True],
    [C3, 128, 1]
  ]
head:
  [
    [Detect,  nc, anchors]
  ]

"""

# Save to file
with open("/kaggle/working/yolo11n.yaml", "w") as f:
    f.write(custom_yaml.strip())

print("Custom 'yolo11n.yaml' written successfully.")

nc: 4  # number of classes
backbone:
  [
    [Conv, 32, 3, 2],
    [Conv, 64, 3, 2],
    [C3, 64, 1],
    [CBAM, 64],
    [C2f, 128, 1],
    [C3, 128, 2],
    [SE, 128],
    [Conv, 256, 3, 2],
    [C3, 256, 2]
  ]

neck:
  [
    [Conv, 256, 3, 1],
    [C3, 256, 1],
    [SE, 256],
    [SPPF, 256],
    [TransformerLayer, 256, 4], # Insert before/after SPPF
    [PAN, 256, 128, True],
    [C3, 128, 1]
  ]

head:
  [
    [Detect, nc, anchors]
  ]

from ultralytics import YOLO

# Build a new model from your custom YAML config
model = YOLO("yolo11n.yaml")
model.load("yolov8s.pt")

result = model.train(
    data="/kaggle/working/weldingg.yaml",
    epochs=100,
    imgsz=640,
    batch=16,
    device=0,
    name="custo",
    optimizer='AdamW',      # change to 'AdamW' or 'auto'
    save=True,
    visualize=True,
    plots=True,

)

!zip -r runs-yolo.zip runs/

"""# Results -novel

"""

from ultralytics import YOLO

model = YOLO("/kaggle/working/runs/detect/custom_yolo4_welding3/weights/best.pt")
val_results = model.val(
    data="/kaggle/working/weldingg.yaml",
    split="val",  # optional, val is default
    imgsz=640,
    device=0
)

!zip -r runs.zip runs/

from thop import profile
from ultralytics import YOLO
import torch

model = YOLO("/kaggle/working/runs/detect/custom_yolo4_welding/weights/best.pt")
dummy_input = torch.randn(1, 3, 640, 640).to("cuda")
flops, params = profile(model.model.to("cuda"), inputs=(dummy_input,))
print(f"FLOPs: {flops/1e9:.2f} GFLOPs | Params: {params/1e6:.2f}M")



